### ISSUE TITLE
Make official?

### ISSUE THREAD

**Issue by 4kimov** [leah-u/sqids-gleam#1]
Found your repo, would love to merge with sqids org and make it official. Looks like porting tests and finishing the readme is the only thing that's left?

**Comment by leah-u** [comment]
Thanks for reaching out, this was just an experiment that I never finished and if I remember correctly it would need a bunch of work still to make it useable. I'm also not sure how much value there is in re-implementing sqids in Gleam over just wrapping the existing Javascript / Erlang implementations.
